language: go
sudo: false
before_install:
        - .travis/gofmt.sh
        - .travis/goimports.sh
        - .travis/gometalinter.sh
        - go get github.com/mattn/goveralls

script:
        - ./configure
        - make clean all test
        - $HOME/gopath/bin/goveralls -service=travis-ci -coverprofile=cover.out

